# public async Task<ActionResult> Login()
GET https://localhost:5000/HttpRequests/Login HTTP/1.1

###

# public async Task<ActionResult> UserDetail(string token)
POST https://localhost:5000/HttpRequests/UserDetail HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseXMiLCJlbWFpbCI6ImVtaWx5LmpvaG5zb25AeC5kdW1teWpzb24uY29tIiwiZmlyc3ROYW1lIjoiRW1pbHkiLCJsYXN0TmFtZSI6IkpvaG5zb24iLCJnZW5kZXIiOiJmZW1hbGUiLCJpbWFnZSI6Imh0dHBzOi8vZHVtbXlqc29uLmNvbS9pY29uL2VtaWx5cy8xMjgiLCJpYXQiOjE3MjcxODUwMzQsImV4cCI6MTcyNzE4NjgzNH0.PBj7Kw4XOORxbddFB4wDNDDMIdUK87F3y3ZTolawfwM


###