# docker compose -f docker.compose.graylog-mongo-opensearch.yml config

name: Graylog

services:

  mongodb:
    image: mongo:6.0.14
    volumes:
      - mongo_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:2.12.0
    volumes:
      - os_data:/usr/share/opensearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=aA132435++
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
      - 9600:9600    

  graylog:
    image: graylog/graylog:6.0
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:      
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper      
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - opensearch
    restart: always
    depends_on:
      - mongodb
      - opensearch
    ports:      
      - 9000:9000      
      - 1514:1514      
      - 1514:1514/udp      
      - 12201:12201      
      - 12201:12201/udp
  
volumes:
  mongo_data:
    driver: local
  os_data:
    driver: local
  graylog_data:
    driver: local