services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports: 
      - 6379:6379 
      - 8001:8001
    volumes:
      - redis_data:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local